version: "3.8"
services:
  moonbeam:
    image: "purestake/moonbeam:latest"
    restart: always
    user: "${UID}:${GID}"`
    ports:
      - "30334:30334"
      - "30333:30333"
    volumes:
      - /var/lib/alphanet-data:/data
    command: "--base-path=/data --chain=alphanet --name=\"$NODE_NAME\" --validator --execution=wasm --wasm-execution=compiled --state-cache-size=1 -- --pruning=archive --name=\"$NODE_NAME (Embedded Relay)\""
