version: "3.8"
services:
  moonbeam:
    image: "purestake/moonbeam:latest"
    restart: always
    ports:
      - "30334:30334"
      - "30333:30333"
    volumes:
      - /var/lib/alphanet-data:/data
    command: "--rpc-cors=all --base-path=/data --chain=alphanet --name=\"$NODE_NAME\" --execution=wasm --wasm-execution=compiled --in-peers=200 --out-peers=200 --pruning=archive --state-cache-size=1 -- --pruning=archive --name=\"$NODE_NAME (Embedded Relay)\""
