#!/bin/bash

curl https://raw.githubusercontent.com/pavlobornia/testnet-tools-public/master/logo/logo.sh | bash
echo "Залітайте в наше Discord комюніті https://discord.gg/weSuTQ2Dx7"
echo "Оновлення ноди Pathfinder до версії 0.3.5 встановленої за гайдом NodesGuru."
cd ~/pathfinder
git fetch
git checkout v0.3.5
cargo build --release --bin pathfinder
mv ~/pathfinder/target/release/pathfinder /usr/local/bin/
cd py
source .venv/bin/activate
PIP_REQUIRE_VIRTUALENV=true pip install -r requirements-dev.txt
pip install --upgrade pip
systemctl restart starknetd
echo "Перевіряємо версію"
if pathfinder -V | grep -q "0.3.5";
then
        echo "Нода оновленна до необхідноі версії"        
fi
sleep 10
echo "Перевіряємо логи"
sleep 10
if dpkg --list | grep -q ccze;
then
        journalctl -n 100 -f -u starknetd.service | ccze -A
else
        journalctl -n 100 -f -u starknetd.service
fi   