#!/bin/bash

curl https://raw.githubusercontent.com/pavlobornia/testnet-tools-public/master/logo/logo.sh | bash
echo "Залітайте в наше Discord комюніті https://discord.gg/weSuTQ2Dx7"
echo "Оновлення ноди Starknet(Pathfinder) встановленої за гайдом NodesGuru."
rustup update
cd ~/pathfinder
git fetch
git checkout v0.4.1
cargo build --release --bin pathfinder
mv ~/pathfinder/target/release/pathfinder /usr/local/bin/
cd py
source .venv/bin/activate
PIP_REQUIRE_VIRTUALENV=true pip install -e .[dev]
pip install --upgrade pip
systemctl restart starknetd.service
echo "Перевіряємо версію..."
pathfinder -V 
echo "Перевіряємо логи"
sleep 5
if dpkg --list | grep -q ccze;
then
        journalctl -n 20 -f -u starknetd.service | ccze -A
else
        journalctl -n 20 -f -u starknetd.service
fi   